### ISSUE TITLE
guppy_basecaller_duplex generated six fastq files from 252 fast5 files.... 

### ISSUE THREAD

**Issue by MostafaYA** [nanoporetech/duplex-tools#10]
Hi, 
I used `guppy_basecaller_duplex` on data produced with the kit SQK-NBD112-24 on FLO-MIN112 flowcell.
 
The Following error appears and out of **252** fast5 files, ONLY **six** fastq files were produced. That I feel is a big loss of data if this 
is ok.
This was the error "repeatd many many times with different sample id"
`[guppy/error] basecalling::PriorityReadQueue::pass_read_pair: Cannot process duplex read pair 9b230638-706f-43b7-a1b4-f2ff63fe410d, 4a1468c9-0093-40b5-8785-328b331cff11 as sample count 324630 is over maximum supported by caller of 160000, putting on output queue`

Despite the above error, `guppy_basecaller_duplex`  said Basecalling  was successful
`*********
Caller time: 1135416 ms, Samples called: 185914147, samples/s: 163741
Finishing up any open output files.
Basecalling completed successfully.
` 

This was my call 
`guppy_basecaller_duplex -i fast5_pass/ -r -s duplex_calls -x auto --kit SQK-NBD112-24  --flowcell                                                     FLO-MIN112  --chunks_per_runner 16 --duplex_pairing_mode from_pair_list  --duplex_pairing_file duplex_output/pair_ids_filtered.txt --trim_barcodes --compress_fastq
`

NB. The config file `q20-fixed-2.0-ft-10M.cfg` was not available is guppy version 6.1.2+e0556ff. Hence I used flags `--kit ` and `--flowcell`. Also I used the config file `dna_r10.4_e8.1_sup.cfg`.  No imporovement

**Comment by cjw85** [comment]
Hi @MostafaYA,

You are better off emailing support@nanoporetech.com or asking this question in the Nanopore Community; it is a different team internally that supports Guppy than those which develop and can support this duplex_tools project.
