### ISSUE TITLE
Can this split read into more than 2 subreads?

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/duplex-tools#12]
We have reads generated from proximal ligation with internal adapters. I was wondering if this tool could search for an adapter and then split the read based on multiple internal adapters being found.

**Comment by cjw85** [comment]
You might like to checkout the [split_on_adapter](https://github.com/nanoporetech/duplex-tools#usage) tool. Guppy can also perform this action as part of basecalling.

**Comment by callumparr** [comment]
Thanks, I will check this out. :)

**Comment by callumparr** [comment]
Is it possible to use the assess split on adapter tool when allowing for multiple read splits. as this does not generate a split_multiple_times.pkl file.

**Comment by onordesjo** [comment]
Right, there's a question about whether the multiple adapters come from true contacts, or whether they come from missed open pore between the reads. That's one reason why I'd be careful to not take a count of reads with multiple internal adapters as a given. There should be a fix coming for that, look out for anything in release notes mentioning "twitchy" event detection

**Comment by callumparr** [comment]
Is this release for duplex_tools or Pore-C? 

That's interesting as I am seeing where its splitting reads but when I align them to reference, it appears to be a contiguous and I also cannot see any alignment to my adapter in blastn. Maybe I have to tune the edit distance.

**Comment by onordesjo** [comment]
It should be a generic feature, not in duplex-tools or pore-c specifically, I'd say keep an eye on the nanopore community site. Could be worth trying to tune the edit distance, but most valuable would be to take a look at the raw reads and see if there is any open pore between the reads

**Comment by callumparr** [comment]
Ah OK. I guess in this case as I have used 1D sequencing adapters I should run duplex_tools split to first use it as intended to separate dsDNA_1-dsDNA_2 ligation events and in silico concatenation. 

And then run again with my custom adapters that should be internal.

**Comment by onordesjo** [comment]
Yep, that sounds like a sensible plan. Sorry, was misparsing what you're doing, unlikely that you have issues with missed splits (on your own custom adapters)
