### ISSUE TITLE
Split_on_adapter and sample type

### ISSUE THREAD

**Issue by Thomieh73** [nanoporetech/duplex-tools#21]
I am trying to see in the documentation for duplex_tools what the reasoning is behind the flags for Sample type in the Split_on_adapter command. I see that it is Native or PCR, but how do I decide which flag to use, and what is the reasoning to have this flag.

**Comment by onordesjo** [comment]
Hi @Thomieh73!

It would depend on if there are PCR primers in the reads (coming from using a PCR protocol during the sample prep). If this is not the case, you can use the Native option.

If you're unsure, the Native option will work for both Native and PCR, but PCR will only work with PCR reads.

Cheers!

**Comment by onordesjo** [comment]
The idea behind also having a PCR mode is that it can decrease the false positive rate for the cases when there are PCR primers in the reads.

**Comment by Thomieh73** [comment]
@onordesjo Thanks for the reply and that makes sense to me. Out of curiosity, how does the PCR mode work? I guess the split_on_adapter tool first searches for the Nanopore sequencing adapters, but when PCR adapters are there, I guess the region next to the adapter is similar between the reads, due to the primers

**Comment by onordesjo** [comment]
Yes, that's correct, the only difference with the PCR mode is how the target to search for is constructed

https://github.com/nanoporetech/duplex-tools/blob/master/duplex_tools/split_on_adapter.py#L49:
```
    targets = {
        'Native': [
            (tail_adapter[:len(tail_adapter) - n_bases_to_mask_tail]
                + middle_sequence
                + head_adapter[n_bases_to_mask_head:])],
        'PCR': [
            (rev_comp(x)
                + tail_adapter[:len(tail_adapter) - n_bases_to_mask_tail]
                + middle_sequence + head_adapter[n_bases_to_mask_head:] + y)
            for x in pcr_primers for y in pcr_primers]
    }
```

So, the sequence to search for in PCR is basically:

`primer(revcomp) - adapter(revcomp) - adapter - primer`

**Comment by Thomieh73** [comment]
Okay, thanks for explaining this. That gives me some insight in the process.
