### ISSUE TITLE
base quality scores

### ISSUE THREAD

**Issue by osilander** [nanoporetech/duplex-tools#24]
For duplex reads I see base quality scores above what I would naively expect. For example, many bases have **{** - which is ASCII 123, or a qscore of 90. My naive expectation would be few qscores above 60. Average qscores across the read are about as expected (Q30+) - and I understand that _average_ qscores are overwhelmingly affected by the lowest qscores in the read.

Long story short, I am wondering whether the per-base qscores been benchmarked by mapping to reference sequences?

Thanks!

**Comment by onordesjo** [comment]
Hi @osilander, I'm not immediately sure. I know that the average qscores are calibrated by mapping to reference sequences. I shall ask around and get back to you!

**Comment by vellamike** [comment]
Hi @osilander - Q scores are indeed calibrated, per-base Q-scores are of course an estimate of how confident the basecaller is in a particular base. Are you seeing evidence that per-base estimates are systematically incorrect?

**Comment by osilander** [comment]
Sorry, no evidence of that at all, I guess just different from my expectation, for example from the start of a reads, bases are:

`GTATTGCTCTTCAGAACCAGCGGAAATTAACACAAAAGTGTCATGATCTTTCACTCACTGGGGACAATGCCATCGGTATTCTTTTTCAGCTGGCAAGGAGCAAATTACAATAATTCACCAACAGTGGAGGGAAACCTCAACATGCAAACCCACTCGCGTG`

and associated qscores:
`G.:>(-0;;/11<PHDH?FC>K{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{X{{[RL{{@[[MR{JX{{{{LM{{{[{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{[{{{{{{{{{{{{{{{{{{{{{{{M[EU[[`

The qscores around that central low qual region translate to 123 123 123 88 123 123 91 82 76 123 123 64 91 91 77 82 123 74 88 123 123 123 123 76 77 123 123 123 91 123 123

and phred adjusted should subtract 33. This means they range from 90 down to 31 in that area. This might be what I expect. What I did not expect was long stretches of q90 (screenshot). 

I will dig a bit deeper (will have to map onto an assembly as I don't have a reference).

<img width="988" alt="Screen Shot 2022-10-26 at 11 39 19 PM" src="https://user-images.githubusercontent.com/25470154/198005913-65437cee-054e-43e3-895c-99cd79024c31.png">
