### ISSUE TITLE
filter_pairs fails if both fastq and aligned bam are present

### ISSUE THREAD

**Issue by olawa** [nanoporetech/duplex-tools#27]
Hi again,
ran the pairing with a guppy output folder with modbases in aligned bam and got almost no valid pairs. Moving the fastq files to a separate folder solved this, with 63% good pairs vs 1% when bam is present.

[09:09:08 - AlignPairs] Processed/Skip/Good: 94%/0%/1%
[09:09:09 - AlignPairs] Good pairs: 3505

[09:17:28 - AlignPairs] Processed/Skip/Good: 95%/0%/63%
[09:17:29 - AlignPairs] Good pairs: 199603

**Comment by onordesjo** [comment]
Hi @olawa, thanks for reporting.

We'll take a look at this and see how best to deal with it. We may need to detect whether it's an unaligned bam (that may come from dorado), and only treat it as a file containing sequences that should be filtered.

**Comment by olawa** [comment]
Yes I guess what happens is that sequence from fastq was found first and the replaced with sequence from bam without flipping strands for aligned reads.

**Comment by olawa** [comment]
I think I may have mixed up two runs here, had one which has ~1% true duplex reads. It works as intended with other runs so I will close this.
