### ISSUE TITLE
Which release of guppy has guppy_basecaller_duplex?

### ISSUE THREAD

**Issue by Kirk3gaard** [nanoporetech/duplex-tools#3]
Hi

I cannot seem to see guppy_basecaller_duplex mentioned in the guppy 5.0.16 release notes. Which version introduced this? I cannot seem to find it in 5.0.15 (guppy_basecall_client,guppy_basecaller,guppy_basecaller_supervisor,guppy_basecall_server).

Best regards
Rasmus

**Comment by fbrennen** [comment]
Hi @Kirk3gaard -- there is a beta version of `guppy_basecaller_duplex` available through the Q20+ community channel:

https://community.nanoporetech.com/posts/q20-community-update

The full version of this is in the next guppy release, which will be available shortly.
