### ISSUE TITLE
Cannot install duplex_tools

### ISSUE THREAD

**Issue by BertVanm** [nanoporetech/duplex-tools#32]
Hi,

I keep getting the error "Could not find a version that satisfies the requirement pod5 (from duplex_tools) (from versions: )
No matching distribution found for pod5 (from duplex_tools)" when trying to install using pip.

Any ideas on how to solve or circumvent this?

Thank you,
Bert

**Comment by onordesjo** [comment]
Hi @BertVanm, thanks for the question.

Can you let me know which version of python you are using? We'd suggest using 3.9. Please also check if you have latest pip installed.

Let me know how you get on

**Comment by BertVanm** [comment]
Hi @onordesjo,
I was trying on python3.5 and 3.6. Switching to 3.9 solved the issue.

Thank you
