### ISSUE TITLE
duplex_tools filter_pairs to have min and max length options?

### ISSUE THREAD

**Issue by Kirk3gaard** [nanoporetech/duplex-tools#4]
Hi
It would be nice to have options for duplex_tools filter_pairs to filter read pairs by length to save time on duplex calling.

Best regards
Rasmus

**Comment by ollenordesjo** [comment]
Hi Rasmus,

Not a bad idea, we could consider adding in a --max_length argument there, I'll see if I can take a look at it tomorrow

**Comment by ollenordesjo** [comment]
Hi @Kirk3gaard, we've added both a --min_length and --max_length option now. Feel free to try it out!
