### ISSUE TITLE
couldn't install on linux or pc

### ISSUE THREAD

**Issue by readingradio** [nanoporetech/duplex-tools#48]
Hello, I am getting an error trying to set up duplex-tools on both linux and windows. I tried updating python and pip, setuptools, wheels, and making sure the directory was in the path variable, all to no avail. Please help.

**Comment by readingradio** [comment]
pip install duplex-tools

error on linux: error: metadata-generation-failed
initial error on linux: ModuleNotFoundError: No module named '_ctypes'

error on windows: Getting requirements to build wheel did not run successfully.
initial error on windows: "." is not recognizable as an internal or external command

**Comment by readingradio** [comment]
Indeed, I used 'duplex_tools' and got those errors; I even tried reinstalling python. Is there a recommended version of python that needs to be used? Thanks.

**Comment by cjw85** [comment]
Can you please provide the full output of running the command

```
pip install --upgrade pip
pip install duplex_tools
```

on your Linux computer. duplex-tools will not work on Windows (it has dependencies that are not available on Windows).
