### ISSUE TITLE
numpy<1.24 incompatible with python3.12 

### ISSUE THREAD

**Issue by jowodo** [nanoporetech/duplex-tools#54]
Hi, 

duplex-tools is incompatible with python 3.12 because of the dependency on numpy<1.24 and any [numpy<1.26 is incompatible with python3.12](https://github.com/numpy/numpy/issues/23808#issuecomment-1676997824). Are there any plans to update the dependency of numpy to higher versions? 

Thanks

**Comment by ollenordesjo** [comment]
Hi @jowodo! 

I'd strongly suggest moving over to the pairing which is happening by default in dorado since we won't be giving pairing updates to duplex-tools. Appreciate that you noticed the incompatibility, but would suggest sticking with <3.12 if you do need to use duplex-tools. 

Thanks!

**Comment by jowodo** [comment]
Thanks for the swift reply! 
Does this mean, that [dorado](https://github.com/nanoporetech/dorado) supersets duplex-tools and 'dorado' should be used instead of duplex-tools? If so, feel free to close this ticket.

**Comment by ollenordesjo** [comment]
Yes, that's correct, the in-built pairing in dorado will replace duplex-tools, so we're recommending using that going forward, feel free to comment in the dorado repository for further pairing questions!

Best
