### ISSUE TITLE
Only works with gzipped fastq files

### ISSUE THREAD

**Issue by mitenjain** [nanoporetech/duplex-tools#6]
In testing this on Ubuntu, I noticed that read splitting only works with gzipped fastq files. 

If the files aren't gzipped, it does not show an error but rather just says:

0it [00:00, ?it/s]
Split 0 reads kept 0 reads

Just raising it here in case it hasn't been noted before.

**Comment by Rasinj** [comment]
Thanks for noticing Miten, we'll definitely sort that, should hopefully be done tomorrow.

**Comment by ollenordesjo** [comment]
Hi Miten, 

Just wanted to check if you checked the --pattern option? If you set it to --pattern "*.fastq", I think things should work as expected. 

I'm realising that it makes sense to process unzipped fastqs by default though, so we'll probably change the defaults.

**Comment by mitenjain** [comment]
Hi Olle, 

You are right. Changing the --pattern does make it work. I think when I tried this before, I changed multiple variables at once which is why it did not work. 

I do agree that altering the defaults may be useful (or just dynamically parse the sequence file based on extension perhaps?).

Thank you for looking into this.

**Comment by ollenordesjo** [comment]
Hi @mitenjain, I've just pushed 0.2.6 which shouldn't be less surprising, and work on both gzipped and non-zipped fastqs. Do let me know if you try it out and if it works as expected. Also happy to take other feedback. 

Many thanks
